version: '3.1'

services:

  psql:
    image: postgres
    container_name: pqsl
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: switcher
    volumes:
      - ./initdb/init-psql.sql:/docker-entrypoint-initdb.d/init.sql

  maria:
    image: mariadb
    container_name: maria
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: switcher
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./initdb/init-maria.sql:/docker-entrypoint-initdb.d/init.sql
